/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ----------------- LIBRERIAS ------------------ */
#include <stdint.h>
#include "magic.c"
#include "gpio_driver_hal.h"
#include "exti_driver_hal.h"
#include "timer_driver_hal.h"
#include "stm32f4xx.h"
#include "maquina_estados_hal.h"

/* ---------------- DEFINICIÓN DE VARIABLES DE LAS CLASES ---------------- */



volatile uint8_t display7segmentFLAG = 0;
volatile uint8_t encoderCLKextiFLAG = 0;
volatile uint8_t encoderSWextiFLAG = 0;

uint16_t contador = 0;
uint8_t miles = 0;
uint8_t centenas = 0;
uint8_t decenas = 0;
uint8_t	unidades = 0;

fsm_states_t stateMachine = {0};
e_PosibleStates state_machine_action(uint8_t event);

GPIO_Handler_t pinH1Led2Board = {0};
GPIO_Handler_t pinEncoderCLK = {0};
GPIO_Handler_t pinEncoderDT = {0};
GPIO_Handler_t pinEncoderSW = {0};
GPIO_Handler_t pinSegmentA = {0};
GPIO_Handler_t pinSegmentB = {0};
GPIO_Handler_t pinSegmentC = {0};
GPIO_Handler_t pinSegmentD = {0};
GPIO_Handler_t pinSegmentE = {0};
GPIO_Handler_t pinSegmentF = {0};
GPIO_Handler_t pinSegmentG = {0};
GPIO_Handler_t pinDigit1 = {0};
GPIO_Handler_t pinDigit2 = {0};
GPIO_Handler_t pinDigit3 = {0};
GPIO_Handler_t pinDigit4 = {0};

Timer_Handler_t display7SegmentTime = {0};
Timer_Handler_t blinkLedPinH1 = {0};

EXTI_Config_t pinExtiEncoderCLK = {0};
EXTI_Config_t pinExtiEncoderSW = {0};



/* ------------------ HEADERS FOR PRIVATE FUNCTIONS ------------- */
void gpioConfig(void);
void extiConfig(void);
void timerConfig(void);
void segmentoON(uint8_t number);
void divideNumber(uint16_t contador);
void mostrarUnidades(void);
void mostrarDecenas(void);
void mostrarCentenas(void);
void mostrarMiles(void);



/* ------------------ CLASS FUNCTIONS ------------ */
int main(void)
{
	gpioConfig();
	timerConfig();
	extiConfig();
    /* Loop forever */
	while(1)
	{


	}return 0;
}

/* ------------------- CONFIG FUNCTIONS ----------- */
void gpioConfig(void)
{
	/* LED BLINKER BOARD */
	pinH1Led2Board.pGPIOx = GPIOH;
	pinH1Led2Board.pinConfig.GPIO_PinNumber = PIN_1;
	pinH1Led2Board.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinH1Led2Board.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinH1Led2Board.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinH1Led2Board.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinH1Led2Board);
	gpio_WritePin(&pinH1Led2Board, SET);

	//Encoder pin CLK
	pinEncoderCLK.pGPIOx = GPIOB;
	pinEncoderCLK.pinConfig.GPIO_PinNumber = PIN_5;
	pinEncoderCLK.pinConfig.GPIO_PinMode = GPIO_MODE_IN;
	pinEncoderCLK.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&pinEncoderCLK);

	//Encoder pin DT
	pinEncoderDT.pGPIOx = GPIOB;
	pinEncoderDT.pinConfig.GPIO_PinNumber = PIN_10;
	pinEncoderDT.pinConfig.GPIO_PinMode = GPIO_MODE_IN;
	pinEncoderDT.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&pinEncoderDT);

	//Encoder pin SW
	pinEncoderSW.pGPIOx = GPIOA;
	pinEncoderSW.pinConfig.GPIO_PinNumber = PIN_8;
	pinEncoderSW.pinConfig.GPIO_PinMode = GPIO_MODE_IN;
	pinEncoderSW.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&pinEncoderSW);

	/* 7 segmentos */
	pinSegmentA.pGPIOx = GPIOB;
	pinSegmentA.pinConfig.GPIO_PinNumber = PIN_12;
	pinSegmentA.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentA.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentA.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentA.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentA);

	/* 7 segmentos */
	pinSegmentB.pGPIOx = GPIOD;
	pinSegmentB.pinConfig.GPIO_PinNumber = PIN_2;
	pinSegmentB.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentB.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentB.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentB.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentB);

	/* 7 segmentos */
	pinSegmentC.pGPIOx = GPIOC;
	pinSegmentC.pinConfig.GPIO_PinNumber = PIN_12;
	pinSegmentC.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentC.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentC.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentC.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentC);

	/* 7 segmentos */
	pinSegmentD.pGPIOx = GPIOC;
	pinSegmentD.pinConfig.GPIO_PinNumber = PIN_9;
	pinSegmentD.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentD.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentD.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentD.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentD);

	/* 7 segmentos */
	pinSegmentE.pGPIOx = GPIOC;
	pinSegmentE.pinConfig.GPIO_PinNumber = PIN_8;
	pinSegmentE.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentE.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentE.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentE.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentE);

	/* 7 segmentos */
	pinSegmentF.pGPIOx = GPIOC;
	pinSegmentF.pinConfig.GPIO_PinNumber = PIN_10;
	pinSegmentF.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentF.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentF.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentF.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentF);

	/* 7 segmentos */
	pinSegmentG.pGPIOx = GPIOC;
	pinSegmentG.pinConfig.GPIO_PinNumber = PIN_11;
	pinSegmentG.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinSegmentG.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinSegmentG.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinSegmentG.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinSegmentG);

	/* 7 segmentos digitos */
	pinDigit1.pGPIOx = GPIOC;
	pinDigit1.pinConfig.GPIO_PinNumber = PIN_6;
	pinDigit1.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinDigit1.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinDigit1.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinDigit1.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinDigit1);
	gpio_WritePin(&pinDigit1, SET);

	/* 7 segmentos digitos */
	pinDigit2.pGPIOx = GPIOC;
	pinDigit2.pinConfig.GPIO_PinNumber = PIN_5;
	pinDigit2.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinDigit2.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinDigit2.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinDigit2.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinDigit2);
	gpio_WritePin(&pinDigit2, SET);

	/* 7 segmentos digitos */
	pinDigit3.pGPIOx = GPIOA;
	pinDigit3.pinConfig.GPIO_PinNumber = PIN_11;
	pinDigit3.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinDigit3.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinDigit3.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinDigit3.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinDigit3);
	gpio_WritePin(&pinDigit3, SET);

	/* 7 segmentos digitos */
	pinDigit4.pGPIOx = GPIOA;
	pinDigit4.pinConfig.GPIO_PinNumber = PIN_12;
	pinDigit4.pinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	pinDigit4.pinConfig.GPIO_PinOutputType = GPIO_OTYPE_PUSHPULL;
	pinDigit4.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	pinDigit4.pinConfig.GPIO_PinOutputSpeed = GPIO_OSPEED_FAST;
	gpio_Config(&pinDigit4);
	gpio_WritePin(&pinDigit4, SET);
}

void timerConfig(void)
{
	blinkLedPinH1.pTIMx = TIM2;
	blinkLedPinH1.TIMx_Config.TIMx_Prescaler = 16000;
	blinkLedPinH1.TIMx_Config.TIMx_Period = 502;
	blinkLedPinH1.TIMx_Config.TIMx_mode = TIMER_UP_COUNTER;
	blinkLedPinH1.TIMx_Config.TIMx_InterruptEnable = TIMER_INT_ENABLE;
	timer_Config(&blinkLedPinH1);
	timer_SetState(&blinkLedPinH1, TIMER_ON);

	display7SegmentTime.pTIMx = TIM3;
	display7SegmentTime.TIMx_Config.TIMx_Prescaler = 16000;
	display7SegmentTime.TIMx_Config.TIMx_Period = 7;
	display7SegmentTime.TIMx_Config.TIMx_mode = TIMER_UP_COUNTER;
	display7SegmentTime.TIMx_Config.TIMx_InterruptEnable = TIMER_INT_ENABLE;
	timer_Config(&display7SegmentTime);
	timer_SetState(&display7SegmentTime, TIMER_ON);

}

void extiConfig(void)
{
	pinExtiEncoderCLK.pGPIOHandler = &pinEncoderCLK;
	pinExtiEncoderCLK.edgeType = EXTERNAL_INTERRUPT_RISING_EDGE;
	exti_Config(&pinExtiEncoderCLK);

	pinExtiEncoderSW.pGPIOHandler = &pinEncoderSW;
	pinExtiEncoderSW.edgeType = EXTERNAL_INTERRUPT_RISING_EDGE;
	exti_Config(&pinExtiEncoderSW);
}

void divideNumber(uint16_t contador)
{
	miles = contador/1000;
	centenas = contador/100 %10;
	decenas = contador/10 %10;
	unidades = contador%10;
}



void segmentoON(uint8_t number)
{
	switch(number)
	{

		case 0:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, SET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, RESET);
		break;

		case 1:
			gpio_WritePin(&pinSegmentA, RESET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, RESET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, RESET);
			gpio_WritePin(&pinSegmentG, RESET);
		break;

		case 2:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, RESET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, SET);
			gpio_WritePin(&pinSegmentF, RESET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 3:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, RESET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 4:
			gpio_WritePin(&pinSegmentA, RESET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, RESET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 5:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, RESET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 6:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, RESET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, SET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 7:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, RESET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, RESET);
			gpio_WritePin(&pinSegmentG, RESET);
		break;

		case 8:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, SET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		case 9:
			gpio_WritePin(&pinSegmentA, SET);
			gpio_WritePin(&pinSegmentB, SET);
			gpio_WritePin(&pinSegmentC, SET);
			gpio_WritePin(&pinSegmentD, SET);
			gpio_WritePin(&pinSegmentE, RESET);
			gpio_WritePin(&pinSegmentF, SET);
			gpio_WritePin(&pinSegmentG, SET);
		break;

		default:
		{
			break;
		}
	}
}

void mostrarUnidades(void)
{
	gpio_WritePin(&pinDigit1, SET);
	gpio_WritePin(&pinDigit2, SET);
	gpio_WritePin(&pinDigit3, SET);
	segmentoON(unidades);
	gpio_WritePin(&pinDigit4, RESET);
}

void mostrarDecenas(void)
{
	gpio_WritePin(&pinDigit1, SET);
	gpio_WritePin(&pinDigit2, SET);
	gpio_WritePin(&pinDigit4, SET);
	segmentoON(decenas);
	gpio_WritePin(&pinDigit3, RESET);
}

void mostrarCentenas(void)
{
	gpio_WritePin(&pinDigit1, SET);
	gpio_WritePin(&pinDigit4, SET);
	gpio_WritePin(&pinDigit3, SET);
	segmentoON(centenas);
	gpio_WritePin(&pinDigit2, RESET);
}

void mostrarMiles(void)
{
	gpio_WritePin(&pinDigit4, SET);
	gpio_WritePin(&pinDigit2, SET);
	gpio_WritePin(&pinDigit3, SET);
	segmentoON(miles);
	gpio_WritePin(&pinDigit1, RESET);
}

/* -------------------- INTERRUPT FUNCTIONS -------------- */
//TIMERS
void Timer2_Callback(void) // Para LED2 de Board (PinH1)
{
	gpio_TogglePin(&pinH1Led2Board);
}

void Timer3_Callback(void) // Para LED2 de Board (PinH1)
{
	display7segmentFLAG = 1;
}

//EXTI
void callback_ExtInt5(void) // pin CLK (PB5)
{
	encoderCLKextiFLAG = 1;
}

void callback_ExtInt8(void) //pin SW (PA8)
{
	encoderSWextiFLAG = 1;
}
