/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* ----------------- LIBRERIAS ------------------ */
#include <stdint.h>
#include "magic.c"
#include "gpio_driver_hal.h"
#include "exti_driver_hal.h"
#include "timer_driver_hal.h"
#include "stm32f4xx.h"

/* ---------------- DEFINICIÓN DE VARIABLES DE LAS CLASES ---------------- */
GPIO_Handler_t pinEncoderCLK = {0};
GPIO_Handler_t pinEncoderDT = {0};
GPIO_Handler_t pinEncoderSW = {0};
GPIO_Handler_t pinEncoderSegmentA = {0};
GPIO_Handler_t pinEncoderSegmentB = {0};
GPIO_Handler_t pinEncoderSegmentC = {0};
GPIO_Handler_t pinEncoderSegmentD = {0};
GPIO_Handler_t pinEncoderSegmentE = {0};
GPIO_Handler_t pinEncoderSegmentF = {0};
GPIO_Handler_t pinEncoderSegmentG = {0};
GPIO_Handler_t pinEncoderDigit1 = {0};
GPIO_Handler_t pinEncoderDigit2 = {0};
GPIO_Handler_t pinEncoderDigit3 = {0};
GPIO_Handler_t pinEncoderDigit4 = {0};

Timer_Handler_t display7SegmentTime = {0};
Timer_Handler_t blinkLedPinH1 = {0};

EXTI_Config_t pinExtiEncoderCLK = {0};
EXTI_Config_t pinExtiEncoderSW = {0};



/* ------------------ HEADERS FOR PRIVATE FUNCTIONS ------------- */
void gpioConfig(void);
void extiConfig(void);
void timerConfig(void);




/* ------------------ CLASS FUNCTIONS ------------ */
int main(void)
{
    /* Loop forever */
	while(1)
	{


	}return 0;
}

/* ------------------- CONFIG FUNCTIONS ----------- */
void gpioConfig(void)
{
	//Encoder
	pinEncoderCLK.pGPIOx = GPIOB;
	pinEncoderCLK.pinConfig.GPIO_PinNumber = PIN_5;
	pinEncoderCLK.pinConfig.GPIO_PinMode = GPIO_MODE_IN;
	pinEncoderCLK.pinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NOTHING;
	gpio_Config(&pinEncoderCLK);


}

/* -------------------- INTERRUPT FUNCTIONS -------------- */

